default_platform(:ios)

platform :ios do

  lane :ci do
    create_xconfig
    `xcodegen`
    
    case git_branch
    when "testflight"
      beta
    else
      build
    end
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build
    deliver(force: true)
  end

  lane :build do
    case git_branch
    when "testflight"
      gym(
        export_method: "app-store",
        include_bitcode: false,
        include_symbols: true
      )
    else
      gym(
        export_method: "development",
        include_bitcode: false,
        include_symbols: false
      )
    end
  end

  lane :mark do
    git_tag
    push_git_tags
  end
end
