devices([
  "iPhone 11 Pro Max",
])

languages([
  "en-US",
])

scheme("Ojol")

clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
